pipeline {
  agent any
  environment {
    VERSION = "1.0.0.${BUILD_NUMBER}"
  }
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'master', url: 'https://github.com/atgt-spl/Supalai.Sale'
      }
    }
    stage('Build') {
      steps {
        sh 'dotnet --info'
		echo "BUILD_NUMBER: ${BUILD_NUMBER}"
		echo "VERSION: ${VERSION}"
        dir('src/Microservices') {
          sh 'dotnet clean'
          sh "dotnet build -p:Version=${VERSION} --configuration Release"
        }
      }
    }
    stage('Publish') {
      steps {
        dir('src/Microservices') {
          sh "dotnet publish -p:Version=${VERSION} Services.SaleOrder/ClassifiedAds.Services.SaleOrder.Api/*.csproj --configuration Release"
        }
      }
    }
  }
}